name: Build and deploy mkdocs to gh-pages
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force